"""add installed skills

Revision ID: 7a5fe513eb30
Revises: 39153ba35d7c
Create Date: 2026-01-12 23:35:35.901154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a5fe513eb30"
down_revision: Union[str, None] = "39153ba35d7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installed_skills",
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("harness_id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.Enum("global", "project", name="install_scope"), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("installed_path", sa.String(length=1024), nullable=False),
        sa.Column("pinned_version", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["harness_id"], ["harnesses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "skill_id", "harness_id", "scope", "project_id", name="uq_installed_skill_identity"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("installed_skills")
    # ### end Alembic commands ###
